export default {
  products: [
    {
      _id: '642340185006beb14d05ec60',
      name: 'Freedom Won Lite Home 10/8 LiFePO4 Battery N-1',
      category: 'Battery',
      image: '/images/inverters.png',
      price: 90000,
      brand: 'Xeon',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
      description:
        'Description: <br>Condition: New product.<br> This Freedom Won Lite Home LiFePO4 battery is the perfect high quality battery for all your residential and industrial solar solutions. The range is from 5KWh to 30KWh batteries.',
    },
    {
      _id: '642340305006beb14d05ec61',
      name: 'Xeon s232 Inverter',
      category: 'Inverters',
      image: '/images/inverter2.png',
      price: 8000,
      brand: 'SolarX',
      rating: 4,
      numReviews: 10,
      countInStock: 10,
      description:
        'Description: <br>Condition: New product.<br> This Freedom Won Lite Home LiFePO4 battery is the perfect high quality battery for all your residential and industrial solar solutions. The range is from 5KWh to 30KWh batteries.',
    },
    {
      _id: '642340435006beb14d05ec62',
      name: 'Triple Power LFP',
      category: 'Inverters',
      image: '/images/TriplePowerLFPwebproduct.png',
      price: 10000,
      brand: 'SolarX',
      rating: 5,
      numReviews: 10,
      countInStock: 8,
      description:
        'Description: <br>Condition: New product.<br> This Freedom Won Lite Home LiFePO4 battery is the perfect high quality battery for all your residential and industrial solar solutions. The range is from 5KWh to 30KWh batteries.',
    },
    {
      _id: '6423405c5006beb14d05ec63',
      name: 'X3 Mega G2 1',
      category: 'Inverters',
      image: '/images/X3-mega-G2-1.png',
      price: 12000,
      brand: 'SolarX',
      rating: 3.5,
      numReviews: 10,
      countInStock: 7,
      description:
        'Description: <br>Condition: New product.<br> This Freedom Won Lite Home LiFePO4 battery is the perfect high quality battery for all your residential and industrial solar solutions. The range is from 5KWh to 30KWh batteries.',
    },
    {
      _id: '64233f4d5006beb14d05ec5c',
      name: 'Mini G4 front',
      category: 'Inverters',
      image: '/images/Mini-G4-front.png',
      price: 14000,
      brand: 'SolarX',
      rating: 3,
      numReviews: 10,
      countInStock: 3,
      description:
        'DC Input: 200% oversizing, 16A current, 40~450V wider MPPT voltage range In-built global MPP scan for higher yields',
    },
    {
      _id: '64233f8d5006beb14d05ec5d',
      name: 'X3 hybrid G4 16',
      category: 'Inverters',
      image: '/images/X3-hybrid-G4.16.png',
      price: 16000,
      brand: 'SolarX',
      rating: 4,
      numReviews: 10,
      countInStock: 4,
      description:
        'Description: <br>Condition: New product.<br> This Freedom Won Lite Home LiFePO4 battery is the perfect high quality battery for all your residential and industrial solar solutions. The range is from 5KWh to 30KWh batteries.',
    },
    {
      _id: '64233fe45006beb14d05ec5e',
      name: 'J1 HES',
      category: 'Inverters',
      image: '/images/J1HES.png',
      price: 16000,
      brand: 'SolarX',
      rating: 4,
      numReviews: 10,
      countInStock: 4,
      description:
        'Description: <br>Condition: New product.<br> This Freedom Won Lite Home LiFePO4 battery is the perfect high quality battery for all your residential and industrial solar solutions. The range is from 5KWh to 30KWh batteries.',
    },
    {
      _id: '64233fff5006beb14d05ec5f',
      name: '1-BAT-front',
      category: 'Inverters',
      image: '/images/1-BAT-front.png',
      price: 16000,
      brand: 'SolarX',
      rating: 4,
      numReviews: 10,
      countInStock: 4,
      description:
        'Description: <br>Condition: New product.<br> This Freedom Won Lite Home LiFePO4 battery is the perfect high quality battery for all your residential and industrial solar solutions. The range is from 5KWh to 30KWh batteries.',
    },
  ],
}
